//! Integration tests for Wave 4 Track J task lifecycle semantics.

use openfang_kernel::OpenFangKernel;
use openfang_runtime::kernel_handle::KernelHandle;
use openfang_types::config::{DefaultModelConfig, KernelConfig};

fn test_config() -> KernelConfig {
    let tmp = tempfile::tempdir().expect("tempdir");
    KernelConfig {
        home_dir: tmp.path().to_path_buf(),
        data_dir: tmp.path().join("data"),
        default_model: DefaultModelConfig {
            provider: "ollama".to_string(),
            model: "test-model".to_string(),
            api_key_env: "OLLAMA_API_KEY".to_string(),
            base_url: None,
        },
        ..KernelConfig::default()
    }
}

#[tokio::test]
async fn test_task_resume_flow_via_kernel_handle() {
    let kernel = OpenFangKernel::boot_with_config(test_config()).expect("kernel boots");

    let task_id = <OpenFangKernel as KernelHandle>::task_post(
        &kernel,
        "Implement parser hardening",
        "Add input validation and retries",
        Some("worker-a"),
        Some("parent-a"),
    )
    .await
    .expect("task created");

    let created = <OpenFangKernel as KernelHandle>::task_get(&kernel, &task_id)
        .await
        .expect("task_get ok")
        .expect("task exists");
    assert_eq!(created["status"], "pending");
    assert_eq!(created["created_by"], "parent-a");

    let claimed = <OpenFangKernel as KernelHandle>::task_claim(&kernel, "worker-a")
        .await
        .expect("task_claim ok")
        .expect("task claimed");
    assert_eq!(claimed["id"], task_id);
    assert_eq!(claimed["status"], "in_progress");

    let no_output = <OpenFangKernel as KernelHandle>::task_output(&kernel, &task_id)
        .await
        .expect("task_output ok");
    assert!(no_output.is_none(), "newly claimed task should not have output");

    let completed = <OpenFangKernel as KernelHandle>::task_update(
        &kernel,
        &task_id,
        Some("completed"),
        None,
        None,
        None,
        Some("Parser hardening completed with 12 tests."),
    )
    .await
    .expect("task_update ok")
    .expect("task updated");
    assert_eq!(completed["status"], "completed");

    let resumed_output = <OpenFangKernel as KernelHandle>::task_output(&kernel, &task_id)
        .await
        .expect("task_output ok")
        .expect("output exists");
    assert!(resumed_output.contains("Parser hardening completed"));

    kernel.shutdown();
}

#[tokio::test]
async fn test_parent_subagent_task_output_aggregation() {
    let kernel = OpenFangKernel::boot_with_config(test_config()).expect("kernel boots");

    let parent_id = "parent-aggregator";
    let child_specs = vec![
        ("child-a", "Analyze auth module", "No critical findings."),
        ("child-b", "Review API schema", "Two minor naming inconsistencies."),
        ("child-c", "Validate migration", "Migration dry-run succeeded."),
    ];

    let mut task_ids = Vec::new();
    for (child, title, result_text) in &child_specs {
        let task_id = <OpenFangKernel as KernelHandle>::task_post(
            &kernel,
            title,
            "Sub-task generated by parent coordinator",
            Some(child),
            Some(parent_id),
        )
        .await
        .expect("task created");

        let _ = <OpenFangKernel as KernelHandle>::task_claim(&kernel, child)
            .await
            .expect("task_claim ok")
            .expect("task claimed");

        let _ = <OpenFangKernel as KernelHandle>::task_update(
            &kernel,
            &task_id,
            Some("completed"),
            None,
            None,
            None,
            Some(result_text),
        )
        .await
        .expect("task_update ok")
        .expect("task updated");

        task_ids.push(task_id);
    }

    let completed = <OpenFangKernel as KernelHandle>::task_list(&kernel, Some("completed"))
        .await
        .expect("task_list ok");

    let parent_completed: Vec<_> = completed
        .into_iter()
        .filter(|t| t["created_by"].as_str() == Some(parent_id))
        .collect();
    assert_eq!(parent_completed.len(), 3, "all subagent tasks should be completed");

    let mut outputs = Vec::new();
    for task_id in &task_ids {
        let out = <OpenFangKernel as KernelHandle>::task_output(&kernel, task_id)
            .await
            .expect("task_output ok")
            .expect("output exists");
        outputs.push(out);
    }

    let aggregate = outputs.join("\n");
    assert!(aggregate.contains("No critical findings."));
    assert!(aggregate.contains("Two minor naming inconsistencies."));
    assert!(aggregate.contains("Migration dry-run succeeded."));

    kernel.shutdown();
}
